# This EventSource selects all services with label
# sveltos: fv and collect all resources matching it
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventSource
metadata:
 name: sveltos-service
spec:
 collectResources: true
 resourceSelectors:
 - group: ""
   version: "v1"
   kind: "Service"
   labelFilters:
   - key: sveltos
     operation: Equal
     value: fv
---
# EventSource supports Lua script as well allowing more complex
# event definition. Any Service is passed to Lua script (obj)
# so script can access any property .
# This is same EventSource as above defined using a script.
apiVersion: lib.projectsveltos.io/v1beta1
kind: EventSource
metadata:
 name: sveltos-service
spec:
 collectResources: true
 resourceSelectors:
 - group: ""
   version: "v1"
   kind: "Service"
   evaluate: |
    function evaluate()
      hs = {}
      hs.matching = false
      hs.message = ""
      if obj.metadata.labels ~= nil then
        for key, value in pairs(obj.metadata.labels) do
          if key == "sveltos" then
            if value == "fv" then
              hs.matching = true
            end
          end
        end
      end
      return hs
    end