# permissions for end users to view eventtriggers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventtrigger-viewer-role
rules:
- apiGroups:
  - lib.projectsveltos.io
  resources:
  - eventtriggers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lib.projectsveltos.io
  resources:
  - eventtriggers/status
  verbs:
  - get
