# permissions for end users to view eventbasedaddons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventbasedaddon-viewer-role
rules:
- apiGroups:
  - lib.projectsveltos.io
  resources:
  - eventbasedaddons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lib.projectsveltos.io
  resources:
  - eventbasedaddons/status
  verbs:
  - get
